# Generated by Django 5.0.6 on 2026-06-06 04:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0003_seed_department_defaults"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("eu_code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "allergens",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LedgerLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_locations",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_age_restricted", models.BooleanField(default=False)),
                ("age_restriction_years", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="departments.department",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[("fixed", "Fixed price"), ("weight_based", "Weight-based (per kg)")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("litre", "Litre"),
                            ("ml", "Millilitre"),
                        ],
                        default="unit",
                        max_length=20,
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=0)),
                ("track_expiry", models.BooleanField(default=False)),
                ("expiry_alert_days", models.IntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="inventory.product"
                    ),
                ),
            ],
            options={
                "db_table": "product_variants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("goods_received", "Goods Received"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("waste", "Waste"),
                            ("markdown", "Markdown"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("weight_kg", models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ("batch_ref", models.CharField(blank=True, max_length=100)),
                ("best_before_date", models.DateField(blank=True, null=True)),
                ("use_by_date", models.DateField(blank=True, null=True)),
                ("order_id", models.IntegerField(blank=True, null=True)),
                ("return_id", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="departments.department",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="staff.staff",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="inventory.ledgerlocation",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_ledger",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariantAllergen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("may_contain", models.BooleanField(default=False)),
                ("allergen", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inventory.allergen")),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergen_links",
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant_allergens",
            },
        ),
        migrations.AddConstraint(
            model_name="ledgerlocation",
            constraint=models.UniqueConstraint(fields=("department", "name"), name="unique_location_per_department"),
        ),
        migrations.AddIndex(
            model_name="inventoryledger",
            index=models.Index(fields=["variant", "-recorded_at"], name="idx_ledger_variant_ts"),
        ),
        migrations.AddIndex(
            model_name="inventoryledger",
            index=models.Index(fields=["department", "-recorded_at"], name="idx_ledger_dept_ts"),
        ),
        migrations.AlterUniqueTogether(
            name="productvariantallergen",
            unique_together={("variant", "allergen")},
        ),
    ]
