# Generated by Django 5.0.6 on 2026-07-03 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_seed_department_defaults'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out')], max_length=20)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clock_events', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_clock_events',
                'ordering': ['-event_at'],
                'indexes': [models.Index(fields=['staff'], name='idx_clock_events_staff_id'), models.Index(fields=['-event_at'], name='idx_clock_events_event_at')],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_commencing', models.DateField()),
                ('shift_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_created', to='staff.staff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_entries', to='departments.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rota_entries', to='staff.staff')),
            ],
            options={
                'db_table': 'rotas',
                'ordering': ['week_commencing', 'shift_date', 'shift_start'],
                'indexes': [models.Index(fields=['staff'], name='idx_rotas_staff_id'), models.Index(fields=['week_commencing'], name='idx_rotas_week_commencing')],
            },
        ),
    ]
