# Generated by Django 5.0.6 on 2026-07-01 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('staff_wages', 'Staff Wages'), ('supplier_payment', 'Supplier Payment'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('maintenance', 'Maintenance'), ('equipment', 'Equipment'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount_pence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('expense_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='staff.staff')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.supplier')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['category'], name='idx_expenses_category'), models.Index(fields=['-expense_date'], name='idx_expenses_expense_date'), models.Index(fields=['recorded_by'], name='idx_expenses_recorded_by')],
            },
        ),
    ]
