# Generated by Django 5.0.6 on 2026-07-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0003_seed_department_defaults'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('scheduled_interval_hours', models.IntegerField(default=4)),
                ('result', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('partial', 'Partial')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField()),
                ('was_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerted_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_alerts', to='staff.staff')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_logs', to='departments.department')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_logs', to='staff.staff')),
            ],
            options={
                'db_table': 'food_safety_cleaning_logs',
                'ordering': ['-cleaned_at'],
                'indexes': [models.Index(fields=['department'], name='idx_cleaning_logs_dept_id'), models.Index(fields=['-cleaned_at'], name='idx_cleaning_logs_cleaned_at'), models.Index(fields=['result'], name='idx_cleaning_logs_result')],
            },
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('was_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperature_logs', to='departments.department')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperature_logs', to='staff.staff')),
            ],
            options={
                'db_table': 'food_safety_temperature_logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['department'], name='idx_temp_logs_department_id'), models.Index(fields=['-checked_at'], name='idx_temp_logs_checked_at'), models.Index(fields=['result'], name='idx_temp_logs_result')],
            },
        ),
    ]
