# Generated by Django 5.0.6 on 2026-07-01 11:34

import apps.core.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0002_alter_order_id_alter_orderitem_id_alter_promotion_id_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', apps.core.fields.EncryptedField()),
                ('last_name', apps.core.fields.EncryptedField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', apps.core.fields.EncryptedField(blank=True, null=True)),
                ('address_line1', apps.core.fields.EncryptedField(blank=True, null=True)),
                ('address_line2', apps.core.fields.EncryptedField(blank=True, null=True)),
                ('city', apps.core.fields.EncryptedField(blank=True, null=True)),
                ('postcode', apps.core.fields.EncryptedField(blank=True, null=True)),
                ('allergen_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('marketing_consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['email'], name='idx_customers_email'), models.Index(fields=['phone'], name='idx_customers_phone'), models.Index(fields=['postcode'], name='idx_customers_postcode')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
                ('lifetime_spend_pence', models.BigIntegerField(default=0)),
                ('points_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='loyalty.customer')),
            ],
            options={
                'db_table': 'loyalty_accounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('adjustment', 'Adjustment'), ('expire', 'Expire')], max_length=20)),
                ('points', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='pos.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_adjustments', to='staff.staff')),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['loyalty_account'], name='idx_loyalty_tx_account_id'), models.Index(fields=['order'], name='idx_loyalty_tx_order_id')],
            },
        ),
    ]
